package com.example.vdllo.mirror.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.vdllo.mirror.db.MirrorEntity;

import com.example.vdllo.mirror.db.MirrorEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig mirrorEntityDaoConfig;

    private final MirrorEntityDao mirrorEntityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        mirrorEntityDaoConfig = daoConfigMap.get(MirrorEntityDao.class).clone();
        mirrorEntityDaoConfig.initIdentityScope(type);

        mirrorEntityDao = new MirrorEntityDao(mirrorEntityDaoConfig, this);

        registerDao(MirrorEntity.class, mirrorEntityDao);
    }
    
    public void clear() {
        mirrorEntityDaoConfig.getIdentityScope().clear();
    }

    public MirrorEntityDao getMirrorEntityDao() {
        return mirrorEntityDao;
    }

}
