package com.example.vdllo.mirror.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "MIRROR_ENTITY".
 */
public class MirrorEntity {

    private Long id;

    public MirrorEntity() {
    }

    public MirrorEntity(Long id) {
        this.id = id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

}
