package com.example.vdllo.mirror.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "MIRROR_ENTITY".
 */
public class MirrorEntity {

    private Long id;
    private String phoneNum;
    private String token;

    public MirrorEntity() {
    }

    public MirrorEntity(Long id) {
        this.id = id;
    }

    public MirrorEntity(Long id, String phoneNum, String token) {
        this.id = id;
        this.phoneNum = phoneNum;
        this.token = token;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPhoneNum() {
        return phoneNum;
    }

    public void setPhoneNum(String phoneNum) {
        this.phoneNum = phoneNum;
    }

    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }

}
